-- Seed Perfumes
INSERT INTO perfumes (id, name, tier, gender, image_url, is_active)
VALUES
  ('w-c-1', 'Dior Hypnotic Poison', 'classic', 'femme', '/catalogues/parfums/femme/Hypnotic-Poison.webp', true),
  ('w-c-2', 'Jean Paul Gaultier Scandal', 'classic', 'femme', '/catalogues/parfums/femme/Scandal.webp', true),
  ('w-c-3', 'Dolce & Gabbana L’Impératrice', 'classic', 'femme', '/catalogues/parfums/femme/Limperatrice.webp', true),
  ('w-c-4', 'Carolina Herrera Good Girl', 'classic', 'femme', '/catalogues/parfums/femme/Good-Girl.webp', true),
  ('w-c-5', 'Giorgio Armani My Way', 'classic', 'femme', '/catalogues/parfums/femme/My-Way.webp', true),
  ('w-c-6', 'Paco Rabanne Olympea', 'classic', 'femme', '/catalogues/parfums/femme/Olympea.webp', true),
  ('w-c-7', 'Burberry Her', 'classic', 'femme', '/catalogues/parfums/femme/Burberry-Her.webp', true),
  ('w-c-8', 'Guerlain Mon Guerlain', 'classic', 'femme', '/catalogues/parfums/femme/Mon-Guerlain.webp', true),
  ('w-c-9', 'Lattafa Yara', 'classic', 'femme', '/catalogues/parfums/femme/Yara.webp', true),
  ('w-c-10', 'Dior Poison Girl', 'classic', 'femme', '/catalogues/parfums/femme/Poison-Girl.webp', true),
  ('w-c-11', 'Yves Saint Laurent Libre Intense', 'classic', 'femme', '/catalogues/parfums/femme/Libre-Intense.webp', true),
  ('w-c-12', 'Yves Rocher Evidence', 'classic', 'femme', '/catalogues/parfums/femme/Evidence.webp', true),
  ('w-c-13', 'Gissah Imperial Valley', 'classic', 'femme', '/catalogues/parfums/femme/Gissah-Imperial-Valley.webp', true),
  ('w-c-14', 'Gucci Flora', 'classic', 'femme', '/catalogues/parfums/femme/Flora-by-Gucci.webp', true),
  ('w-c-15', 'Elie Saab Le Parfum', 'classic', 'femme', '/catalogues/parfums/femme/Elie-Saab-Le-Parfum.webp', true),
  ('w-c-16', 'Francis Kurkdjian Baccarat Rouge 540', 'classic', 'femme', '/catalogues/parfums/femme/Baccarat-Rouge-540.webp', true),
  ('w-c-17', 'Alam Otur Taj', 'classic', 'femme', '/catalogues/parfums/femme/Taj.webp', true),
  ('w-c-18', 'Dolce & Gabbana The One Femme', 'classic', 'femme', '/catalogues/parfums/femme/The-One-Femme.webp', true),
  ('w-c-19', 'Dior J’adore', 'classic', 'femme', '/catalogues/parfums/femme/Jadore.webp', true),
  ('w-n-1', 'Kayali 28', 'niche', 'femme', '/catalogues/parfums/femme/Kayali-28.webp', true),
  ('w-n-2', 'Kayali Utopia Vanilla', 'niche', 'femme', '/catalogues/parfums/femme/Utopia-Vanille.webp', true),
  ('w-n-3', 'Kayali Marshmallow', 'niche', 'femme', '/catalogues/parfums/femme/Marshmallow.webp', true),
  ('w-n-4', 'MFK Baccarat Rouge 540 Extrait', 'niche', 'femme', '/catalogues/parfums/femme/Baccarat-Rouge-540-Extrait.webp', true),
  ('w-n-5', 'Maison Marly Delina', 'niche', 'femme', '/catalogues/parfums/femme/Delina.webp', true),
  ('m-c-1', 'Dior Sauvage Elixir', 'classic', 'homme', '/catalogues/parfums/homme/Sauvage-Elixir.webp', true),
  ('m-c-2', 'Armani Stronger With You', 'classic', 'homme', '/catalogues/parfums/homme/Stronger-With-You.webp', true),
  ('m-c-3', 'Tom Ford Black Orchid', 'classic', 'homme', '/catalogues/parfums/homme/Black-Orchid.webp', true),
  ('m-c-4', 'Dior Homme Intense', 'classic', 'homme', '/catalogues/parfums/homme/Dior-Homme-Intense.webp', true),
  ('m-c-5', 'Dunhill Desire', 'classic', 'homme', '/catalogues/parfums/homme/Desire.webp', true),
  ('m-c-6', 'Dunhill Desire Blue', 'classic', 'homme', '/catalogues/parfums/homme/Desire-Blue.webp', true),
  ('m-c-7', 'JPG Ultra Male', 'classic', 'homme', '/catalogues/parfums/homme/Ultra-Male.webp', true),
  ('m-c-8', 'Dior Sauvage', 'classic', 'homme', '/catalogues/parfums/homme/Sauvage.webp', true),
  ('m-c-9', 'Chanel Bleu', 'classic', 'homme', '/catalogues/parfums/homme/Bleu-de-Chanel.webp', true),
  ('m-c-10', 'JPG Le Male Elixir', 'classic', 'homme', '/catalogues/parfums/homme/Le-Male-Elixir.webp', true),
  ('m-c-11', 'Mont Blanc Legend', 'classic', 'homme', '/catalogues/parfums/homme/Legend.webp', true),
  ('m-c-12', 'Armani You Intensely', 'classic', 'homme', '/catalogues/parfums/homme/You-Intensely.webp', true),
  ('m-c-13', 'Lancôme Oud Bouquet', 'classic', 'homme', '/catalogues/parfums/homme/Oud-Bouquet.webp', true),
  ('m-c-14', 'Paco Rabanne One Million', 'classic', 'homme', '/catalogues/parfums/homme/One-Million.webp', true),
  ('m-c-15', 'Paco Rabanne Black XS', 'classic', 'homme', '/catalogues/parfums/homme/Black-XS.webp', true),
  ('m-c-16', 'Azzaro Wanted', 'classic', 'homme', '/catalogues/parfums/homme/Wanted.webp', true),
  ('m-c-17', 'Paco Rabanne XS L’Exces', 'classic', 'homme', '/catalogues/parfums/homme/XS-Lexces.webp', true),
  ('m-c-18', 'YSL La Nuit de L’Homme', 'classic', 'homme', '/catalogues/parfums/homme/La-Nuit-de-LHomme.webp', true),
  ('m-c-19', 'Alan Bray L’Homme Legend', 'classic', 'homme', '/catalogues/parfums/homme/Lhomme-Legend.webp', true),
  ('m-n-1', 'LV Ombre Nomade', 'niche', 'homme', '/catalogues/parfums/homme/Ombre-Nomade.webp', true),
  ('m-n-2', 'LV Imagination', 'niche', 'homme', '/catalogues/parfums/homme/Imagination.webp', true),
  ('m-n-3', 'Xerjoff Erba Pura', 'niche', 'homme', '/catalogues/parfums/homme/Erba-Pura.webp', true),
  ('m-n-4', 'Xerjoff Naxos', 'niche', 'homme', '/catalogues/parfums/homme/Naxos.webp', true),
  ('m-n-5', 'Tom Ford Tobacco Vanille', 'niche', 'homme', '/catalogues/parfums/homme/Tobacco-Vanille.webp', true)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  tier = EXCLUDED.tier,
  gender = EXCLUDED.gender,
  image_url = EXCLUDED.image_url,
  is_active = EXCLUDED.is_active;

-- Seed Inventory Defaults
INSERT INTO inventory (perfume_id, stock, low_stock_threshold, updated_at)
VALUES
  ('w-c-1', 0, 5, NOW()),
  ('w-c-2', 0, 5, NOW()),
  ('w-c-3', 0, 5, NOW()),
  ('w-c-4', 0, 5, NOW()),
  ('w-c-5', 0, 5, NOW()),
  ('w-c-6', 0, 5, NOW()),
  ('w-c-7', 0, 5, NOW()),
  ('w-c-8', 0, 5, NOW()),
  ('w-c-9', 0, 5, NOW()),
  ('w-c-10', 0, 5, NOW()),
  ('w-c-11', 0, 5, NOW()),
  ('w-c-12', 0, 5, NOW()),
  ('w-c-13', 0, 5, NOW()),
  ('w-c-14', 0, 5, NOW()),
  ('w-c-15', 0, 5, NOW()),
  ('w-c-16', 0, 5, NOW()),
  ('w-c-17', 0, 5, NOW()),
  ('w-c-18', 0, 5, NOW()),
  ('w-c-19', 0, 5, NOW()),
  ('w-n-1', 0, 5, NOW()),
  ('w-n-2', 0, 5, NOW()),
  ('w-n-3', 0, 5, NOW()),
  ('w-n-4', 0, 5, NOW()),
  ('w-n-5', 0, 5, NOW()),
  ('m-c-1', 0, 5, NOW()),
  ('m-c-2', 0, 5, NOW()),
  ('m-c-3', 0, 5, NOW()),
  ('m-c-4', 0, 5, NOW()),
  ('m-c-5', 0, 5, NOW()),
  ('m-c-6', 0, 5, NOW()),
  ('m-c-7', 0, 5, NOW()),
  ('m-c-8', 0, 5, NOW()),
  ('m-c-9', 0, 5, NOW()),
  ('m-c-10', 0, 5, NOW()),
  ('m-c-11', 0, 5, NOW()),
  ('m-c-12', 0, 5, NOW()),
  ('m-c-13', 0, 5, NOW()),
  ('m-c-14', 0, 5, NOW()),
  ('m-c-15', 0, 5, NOW()),
  ('m-c-16', 0, 5, NOW()),
  ('m-c-17', 0, 5, NOW()),
  ('m-c-18', 0, 5, NOW()),
  ('m-c-19', 0, 5, NOW()),
  ('m-n-1', 0, 5, NOW()),
  ('m-n-2', 0, 5, NOW()),
  ('m-n-3', 0, 5, NOW()),
  ('m-n-4', 0, 5, NOW()),
  ('m-n-5', 0, 5, NOW())
ON CONFLICT (perfume_id) DO NOTHING;
