export const MOROCCAN_CITIES: string[] = [
    "Casablanca",
    "Rabat",
    "Salé",
    "Marrakech",
    "Tanger",
    "Fès",
    "Agadir",
    "Meknès",
    "Oujda",
    "Tétouan",
    "Kénitra",
    "El Jadida",
    "Safi",
    "Mohammedia",
    "Nador",
    "Khouribga",
    "Settat",
    "Béni Mellal",
    "Larache",
    "Ksar El Kebir",
    "Al Hoceïma",
    "Taza",
    "Dakhla",
    "Laâyoune",
    "Guelmim",
    "Taroudant",
    "Essaouira",
    "Errachidia",
    "Ouarzazate",
    "Ait Melloul",
    "Berkane",
    "Khemisset",
    "Tiznit",
    "Sidi Kacem",
    "Sidi Slimane",
    "Oued Zem",
    "Youssoufia",
    "Sefrou",
    "Taourirt",
    "Guercif",
    "Kelaa Sraghna",
    "Fnideq",
    "Martil",
    "Skhirat",
    "Temara",
    "Ain Harrouda",
    "Azrou",
    "Ifrane",
    "Khénifra",
    "Midelt",
    "Tinghir",
    "Zagora",
    "Tan-Tan",
    "Boujdour",
    "Smara",
    "Biougra",
    "Inezgane",
    "Aourir",
    "Imzouren",
    "Chefchaouen",
    "Ouezzane",
    "Sidi Ifni",
    "Tarfaya",
    "Jerada",
    "Ahfir",
    "Fquih Ben Salah",
    "Souk El Arbaa",
    "Bouskoura",
    "Berrechid",
    "Nouaceur",
    "Tiflet",
    "Kalaat Mgouna",
    "Asilah",
    "Azemmour",
    "Ait Ourir",
    "Boulemane",
    "Demnate",
    "Beni Ansar",
    "Mdiq",
    "Had Soualem",
    "Sidi Bennour",
    "Ben Guerir",
    "Chichaoua",
    "Sidi Yahya El Gharb",
    "Bhalil",
    "Tifnit",
    "Tamansourt",
    "Drarga",
    "Ain Aouda",
    "Sidi Rahal",
    "Tamesna",
    "Akhfenir",
    "Bouznika",
    "Aourir n Agadir",
    "Ksar Sghir",
    "Ain Taoujdate",
    "Tahla",
    "Bouarfa",
    "Bab Berred",
    "Oulad Teima",
    "Jorf El Melha",
    "Bni Hadifa",
    "Saidia",
    "Benslimane",
];
